export {
  DEFAULT_CHUNK_MIN_CHARS,
  CHUNK_KEY_SEP,
  splitterVersionOf,
  resolveChunkSurface,
  parentShaOf,
  embeddedChunkText,
  chunkParentKeyId,
  planChunks,
  syncChunkSurface,
  syncChunkSurfaces,
  type ChunkPlan,
} from './engine';
export {
  sharedChunkStore,
  parentShaSql,
  SHARED_CHUNK_EMBEDDED_TEXT_SQL,
  type SharedChunkStoreOptions,
} from './shared-store';
export {
  chunkEmbedTargets,
  validateChunkEmbedTarget,
  selectPendingChunks,
  embedPendingChunks,
  type ChunkEmbedder,
  type PendingChunk,
  type EmbedPendingChunksOptions,
  type EmbedPendingChunksResult,
} from './embed';
export {
  chunkAwareVectorLeg,
  chunkAwareVectorLegSql,
  chunkVectorTableOf,
  type ChunkAwareVectorLegOptions,
  type ChunkAwareLegRow,
  type ChunkLegMode,
  type ChunkLegScan,
  type ParentVectorColumns,
  type SpaceFilterColumns,
} from './vector-leg';
export type {
  ChunkSurface,
  ChunkSplitter,
  WindowChunkSplitter,
  MarkdownChunkSplitter,
  ChunkKeyColumn,
  ResolvedChunkSurface,
  ChunkStore,
  ChunkVectorTable,
  ChunkEmbedTarget,
  StaleParent,
  ExistingChunk,
  PlannedChunk,
  ChunkRowToWrite,
  ChunkWriteMeta,
  ChunkHash,
  ChunkSyncLogger,
  ChunkSurfaceSyncStats,
  ChunkSyncResult,
  ChunkSyncOptions,
} from './types';
