export {
  DEFAULT_CHUNK_MIN_CHARS,
  CHUNK_KEY_SEP,
  splitterVersionOf,
  resolveChunkSurface,
  parentShaOf,
  embeddedChunkText,
  chunkParentKeyId,
  planChunks,
  syncChunkSurface,
  syncChunkSurfaces,
  type ChunkPlan,
} from './engine';
export { sharedChunkStore, parentShaSql, type SharedChunkStoreOptions } from './shared-store';
export {
  chunkAwareVectorLeg,
  chunkAwareVectorLegSql,
  chunkVectorTableOf,
  type ChunkAwareVectorLegOptions,
  type ChunkAwareLegRow,
  type ChunkLegMode,
  type ParentVectorColumns,
  type SpaceFilterColumns,
} from './vector-leg';
export type {
  ChunkSurface,
  ChunkSplitter,
  WindowChunkSplitter,
  MarkdownChunkSplitter,
  ChunkKeyColumn,
  ResolvedChunkSurface,
  ChunkStore,
  StaleParent,
  ExistingChunk,
  PlannedChunk,
  ChunkRowToWrite,
  ChunkWriteMeta,
  ChunkHash,
  ChunkSyncLogger,
  ChunkSurfaceSyncStats,
  ChunkSyncResult,
  ChunkSyncOptions,
} from './types';
