/**
 * Golden tests for the splitters: the library must reproduce, byte for byte,
 * what the chunkers produced BEFORE they moved here.
 *
 * __fixtures__/chunk-golden.v1.json was generated by running the pre-move
 * functions (papercusp's turn-chunk-sync `splitTurnChunks` and doc-embed-sync
 * `splitDocSections`, at the blob SHAs recorded in its `generatedFrom`) over a
 * synthetic corpus built to hit every branch: window lengths around each
 * boundary, the chunk cap, degenerate overlap, surrogate pairs on window edges,
 * both fence styles, duplicate and empty slugs, CRLF, oversized sections, a
 * single over-long line, and both the section cap and the part cap.
 *
 * Why it matters: stored chunks and their embeddings were produced by the old
 * code. If the library split differently, every stored chunk would read as
 * stale and be re-embedded (1.2M session-turn chunks, 14.5k doc sections).
 *
 * Never regenerate the fixture from the library itself — that turns this test
 * into a tautology. A deliberate splitter change needs a new fixture version
 * AND a migration story for the rows already stored.
 */
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { splitMarkdown, splitWindows, type WindowSplitOptions } from './chunk';

type Part = string | { s: string; n: number };
interface Fixture {
  markdownOptions: { maxChars: number; minChars: number; headingDepth: number; maxSections: number; maxRows: number };
  windows: Array<{ name: string; parts: Part[]; opts: WindowSplitOptions; textSha: string; chunkShas: string[]; chunkLengths: number[] }>;
  markdown: Array<{
    name: string;
    title: string;
    parts: Part[];
    bodySha: string;
    sections: Array<{ anchor: string; heading: string | null; contentSha: string; contentLength: number }>;
  }>;
}

const fixture = JSON.parse(
  readFileSync(new URL('./__fixtures__/chunk-golden.v1.json', import.meta.url), 'utf8'),
) as Fixture;
const expand = (parts: Part[]): string => parts.map((p) => (typeof p === 'string' ? p : p.s.repeat(p.n))).join('');
const sha = (s: string): string => createHash('sha256').update(s).digest('hex');

describe('splitWindows reproduces the pre-move session-turn splitter', () => {
  it('fixture inputs expand to the texts the pins were taken from', () => {
    for (const c of fixture.windows) expect(sha(expand(c.parts)), c.name).toBe(c.textSha);
  });

  for (const c of fixture.windows) {
    it(c.name, () => {
      const chunks = splitWindows(expand(c.parts), c.opts);
      expect(chunks.map((x) => x.length)).toEqual(c.chunkLengths);
      expect(chunks.map(sha)).toEqual(c.chunkShas);
    });
  }
});

describe('splitMarkdown reproduces the pre-move doc-section splitter', () => {
  it('fixture inputs expand to the bodies the pins were taken from', () => {
    for (const c of fixture.markdown) expect(sha(expand(c.parts)), c.name).toBe(c.bodySha);
  });

  for (const c of fixture.markdown) {
    it(c.name, () => {
      const got = splitMarkdown(expand(c.parts), fixture.markdownOptions).map((s) => ({
        anchor: s.anchor,
        // The old splitter titled each section `page › heading`; the heading it
        // used is the last entry of the library's heading path.
        heading: s.headingPath.length === 0 ? null : s.headingPath[s.headingPath.length - 1],
        contentSha: sha(s.content),
        contentLength: s.content.length,
      }));
      expect(got).toEqual(c.sections);
    });
  }
});

describe('the golden comparison can fail', () => {
  // A comparison that cannot fail proves nothing. These off-by-one variants of
  // the real splitter must each disagree with the pins somewhere.
  const noEarlyStop = (text: string, o: WindowSplitOptions): string[] => {
    const out: string[] = [];
    for (let s = 0; s < text.length && out.length < o.maxChunks; s += Math.max(1, o.size - o.overlap)) {
      out.push(text.slice(s, s + o.size));
    }
    return out;
  };
  const mismatches = (split: (t: string, o: WindowSplitOptions) => string[]): number =>
    fixture.windows.filter((c) => JSON.stringify(split(expand(c.parts), c.opts).map(sha)) !== JSON.stringify(c.chunkShas)).length;

  it('the real splitter matches every pin (calibration)', () => {
    expect(mismatches(splitWindows)).toBe(0);
  });

  it('a splitter that emits a trailing runt window is caught', () => {
    expect(mismatches(noEarlyStop)).toBeGreaterThan(0);
  });

  it('a markdown splitter with a different part cap is caught', () => {
    const drifted = fixture.markdown.filter((c) => {
      const got = splitMarkdown(expand(c.parts), { ...fixture.markdownOptions, maxChars: 1999 });
      return JSON.stringify(got.map((s) => sha(s.content))) !== JSON.stringify(c.sections.map((s) => s.contentSha));
    });
    expect(drifted.length).toBeGreaterThan(0);
  });
});
